version: '3.0'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: siftli
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
        - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
volumes:
  database_data: {}